# Generated by Django 2.2.6 on 2019-10-19 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Europe', 'Europe'), ('Africa', 'Africa'), ('Asia', 'Asia'), ('North America', 'North America'), ('No Specific Region', 'No Specific Region')], default='No Specific Region', max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('History', 'History'), ('Science', 'Science')], default='History', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Time_Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era', models.CharField(choices=[('Early Modern', 'Early Modern'), ('Modern', 'Modern')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_url', models.URLField(verbose_name='Web Address')),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=225)),
                ('title', models.CharField(max_length=150)),
                ('era', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_entry', to='videos.Time_Period')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_entry', to='videos.Region')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_entry', to='videos.Subject')),
            ],
        ),
    ]
