# Generated by Django 2.2.6 on 2019-10-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_entry_resid'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_entry',
            name='vid_player',
            field=models.CharField(choices=[('youtube', 'youtube'), ('vimeo', 'vimeo')], default='youtube', max_length=40),
        ),
    ]
