# Generated by Django 2.2.6 on 2019-10-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_entry_vid_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_entry',
            name='vid_player',
            field=models.CharField(choices=[('youtube', 'youtube'), ('vimeo', 'vimeo'), ('national archives', 'national archives')], default='youtube', max_length=40),
        ),
    ]
