# Generated by Django 2.2.6 on 2019-10-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_formal_science_natural_science_natural_science_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='topic',
            field=models.CharField(choices=[('History', 'History'), ('Science', 'Science')], max_length=50),
        ),
    ]
